package automatedsequence.gui;

import automatedsequence.MP3Player;
import automatedsequence.RandomizeOCanada;
import automatedsequence.Timer;
import automatedsequence.constants.PathConstants;
import automatedsequence.dateAndTime.SuperCalendar;
import automatedsequence.fileInput.Line;
import automatedsequence.fileInput.ReadOCanadaFile;
import automatedsequence.fileInput.ReadScheduleFile;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.AbstractListModel;
import javax.swing.ListSelectionModel;

/**
 * Purpose: Main Program Class
 *
 * @author Brian Ho, Max Romanoff, Conor Norman 
 * June 5 2014
 */
public class MainProgram extends javax.swing.JFrame {

    private static MP3Player player = new MP3Player();
    private ReadScheduleFile scheduleFile = new ReadScheduleFile(); // run the constructor
    private ReadOCanadaFile oCanadaFile = new ReadOCanadaFile(); // run the constructor
    private RandomizeOCanada oCanada = new RandomizeOCanada();
    private String time, information; // storing time and ocanada info
    private SuperCalendar calendar = new SuperCalendar();

    private AbstractListModel tableModel;
    private String[] fileInformation;

    /**
     * Creates new form MainProgram
     */
    public MainProgram() {
        populateScheduledBox(false);
        initComponents(); // initializes all the components in the gui
    }

    /**
     * Method gets the instance of the mp3 player
     *
     * @return instance of mp3 player
     */
    public static MP3Player getMP3PlayerInstance() {
        return player;
    }

    /**
     * Method updates the scheduled box
     *
     * @param refresh true if updating
     */
    public void populateScheduledBox(boolean refresh) {
        fileInformation = new String[ReadScheduleFile.getScheduledEventData().size()]; // match size of arralist
        for (Line genericEventData : ReadScheduleFile.getScheduledEventData()) { // loop through all indexes
            fileInformation[genericEventData.getEventID()] = "[" + Line.getFormattedTime(ReadScheduleFile.getScheduledEventData().get(genericEventData.getEventID()).getStartTime()) + " - " + Line.getFormattedTime(ReadScheduleFile.getScheduledEventData().get(genericEventData.getEventID()).getEndTime()) + "] " + ReadScheduleFile.getScheduledEventData().get(genericEventData.getEventID()).getName(); // format and populate
        }
        tableModel = new AbstractListModel() {

            public int getSize() {
                return fileInformation.length;
            }

            public Object getElementAt(int i) {
                return fileInformation[i];
            }
        };
        if (refresh) { // only true when updating
            scheduledTasks.setModel(tableModel); // set model
            scheduledTasks.revalidate(); // revalidate
            scheduledTasks.repaint(); // refreshes
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scheduleCommandButton = new javax.swing.JButton();
        infoPane = new javax.swing.JScrollPane();
        informationBox = new javax.swing.JTextArea();
        infoLabel = new javax.swing.JLabel();
        scheduledTasksLabel = new javax.swing.JLabel();
        dateAndTimeLabel = new javax.swing.JLabel();
        overrideToggleButton = new javax.swing.JToggleButton();
        propertiesButton = new javax.swing.JButton();
        postponeToggleButton = new javax.swing.JToggleButton();
        postponeDurationInMinutes = new javax.swing.JTextField();
        minutesLabel = new javax.swing.JLabel();
        scheduleHolidaysButton = new javax.swing.JButton();
        startNowButton = new javax.swing.JButton();
        scheduledTasksPane = new javax.swing.JScrollPane();
        scheduledTasks = new javax.swing.JList();
        deleteButton = new javax.swing.JButton();
        modifyTasksButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Automator (Brian Ho, Maxim Romanoff, Conor Norman)");
        setResizable(false);

        scheduleCommandButton.setText("Schedule Command");
        scheduleCommandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleCommandButtonActionPerformed(evt);
            }
        });

        informationBox.setColumns(1);
        informationBox.setRows(1);
        informationBox.setEditable(false); // cannot edit text being displayed
        informationBox.setText(information);
        infoPane.setViewportView(informationBox);

        infoLabel.setText("Info");

        scheduledTasksLabel.setText("SCHEDULED TASKS");

        dateAndTimeLabel.setText(time);

        overrideToggleButton.setText("Override");
        overrideToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overrideToggleButtonActionPerformed(evt);
            }
        });

        propertiesButton.setText("Properties");
        propertiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertiesButtonActionPerformed(evt);
            }
        });

        postponeToggleButton.setText("Postpone");
        postponeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postponeToggleButtonActionPerformed(evt);
            }
        });

        postponeDurationInMinutes.setText("5");

        minutesLabel.setText("Minutes");

        scheduleHolidaysButton.setText("Schedule Holidays");
        scheduleHolidaysButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleHolidaysButtonActionPerformed(evt);
            }
        });

        startNowButton.setText("START NOW");
        startNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNowButtonActionPerformed(evt);
            }
        });

        scheduledTasks.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        scheduledTasks.setModel(tableModel);
        scheduledTasksPane.setViewportView(scheduledTasks);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        modifyTasksButton.setText("MODIFY");
        modifyTasksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyTasksButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/pic.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(dateAndTimeLabel))
                    .addComponent(scheduleHolidaysButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scheduleCommandButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(propertiesButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modifyTasksButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scheduledTasksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(overrideToggleButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(postponeToggleButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(postponeDurationInMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(minutesLabel)
                            .addGap(18, 18, 18)
                            .addComponent(startNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(scheduledTasksPane)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scheduledTasksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scheduledTasksPane, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(overrideToggleButton)
                            .addComponent(postponeToggleButton)
                            .addComponent(postponeDurationInMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minutesLabel)
                            .addComponent(startNowButton))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scheduleCommandButton)
                            .addComponent(propertiesButton)
                            .addComponent(modifyTasksButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(scheduleHolidaysButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateAndTimeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(infoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        new Thread(){
            public void run(){
                while (true){
                    Calendar c= new GregorianCalendar();
                    String dayOfWeek = (calendar.getDayOfWeek(c.get(Calendar.DAY_OF_WEEK)));
                    String month = (calendar.getMonth(c.get(Calendar.MONTH) + 1)); // because starts at 0
                    int dayOfMonth = c.get(Calendar.DAY_OF_MONTH);
                    int year = c.get(Calendar.YEAR);
                    int hour = c.get(Calendar.HOUR_OF_DAY);
                    int minute = c.get(Calendar.MINUTE);
                    int sec = c.get(Calendar.SECOND);
                    time = dayOfWeek + " " + month + " " + dayOfMonth + " " + year + " [EDT " + hour +":" + ((minute < 10) ? "0" + minute : minute) + ":" + ((sec < 10) ? "0" + sec : sec) + "]";
                    dateAndTimeLabel.setText(time);
                    information = "[INFO] O'CANADA VERSION " + Timer.getOCanadaVersion() +" SELECTED";
                    informationBox.setText(!Timer.isOCanadaPlaying() ? "Waiting to start O'Canada..." : information);

                    try {
                        Thread.sleep(1000); // loop once every second, reduces toll on cpu
                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }
                }
            }
        }.start();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method stops the music when the override button is toggled true
     *
     * @param evt
     */
    private void overrideToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overrideToggleButtonActionPerformed
        player.Stop(); // stops the music from playing
    }//GEN-LAST:event_overrideToggleButtonActionPerformed

    /**
     * Method creates a commandsGUI object and launches a new window
     *
     * @param evt
     */
    private void scheduleCommandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleCommandButtonActionPerformed
        if (!postponeToggleButton.isSelected()) { // if postpone button is not selected
            CommandScheduler commandsGUI = new CommandScheduler(); // command gui object
            commandsGUI.setLocationRelativeTo(null); // centers window
            commandsGUI.setVisible(true); // make visible
        }
    }//GEN-LAST:event_scheduleCommandButtonActionPerformed

    /**
     * Method postpones the events by the duration that the user enters and when
     * button is released, value resets to normal
     *
     * @param evt
     */
    private void postponeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postponeToggleButtonActionPerformed
        for (Line genericEventData : ReadScheduleFile.getScheduledEventData()) { // loop through all indexes
            if (postponeToggleButton.isSelected()) {
                if (!genericEventData.getPath().equalsIgnoreCase("NOPATH")) { // if it is not a holiday
                    genericEventData.postponeStartTime(Integer.parseInt(postponeDurationInMinutes.getText()));
                    genericEventData.postponeEndTime(Integer.parseInt(postponeDurationInMinutes.getText()));
                }
                postponeDurationInMinutes.setEditable(false); // avoid potential bug, does not let user change value after button is pressed
                populateScheduledBox(true); // refreshes info box
            } else {
                if (!genericEventData.getPath().equalsIgnoreCase("NOPATH")) { // if it is not a holiday
                    genericEventData.postponeStartTime(-Integer.parseInt(postponeDurationInMinutes.getText()));
                    genericEventData.postponeEndTime(-Integer.parseInt(postponeDurationInMinutes.getText()));
                }
                postponeDurationInMinutes.setEditable(true);
                populateScheduledBox(true); // refreshes info box
            }
        }
    }//GEN-LAST:event_postponeToggleButtonActionPerformed

    /**
     * Method creates a propertiesGUI object and launches a new window
     *
     * @param evt
     */
    private void propertiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertiesButtonActionPerformed
        if (!postponeToggleButton.isSelected()) { // if postpone button is not selected
            Properties propertiesGUI = new Properties(); // properties gui object
            propertiesGUI.setLocationRelativeTo(null); // centers window
            propertiesGUI.setVisible(true); // make visible
        }
    }//GEN-LAST:event_propertiesButtonActionPerformed

    /**
     * Method plays selected file in "SCHEDULED TASKS" box when clicked
     *
     * @param evt
     */
    private void startNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNowButtonActionPerformed
        if (!overrideToggleButton.isSelected()) { // if the override button is not selected
            if (scheduledTasks.getSelectedIndex() >= 0 && scheduledTasks.getSelectedIndex() < ReadScheduleFile.getScheduledEventData().size()) {
                player.Play(ReadScheduleFile.getScheduledEventData().get(scheduledTasks.getSelectedIndex()).getPath());
            }
        }
    }//GEN-LAST:event_startNowButtonActionPerformed

    /**
     * Method creates a holidaysGUI object and launches a new window
     *
     * @param evt
     */
    private void scheduleHolidaysButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleHolidaysButtonActionPerformed
        if (!postponeToggleButton.isSelected()) { // if postpone button is not selected
            HolidayScheduler holidaysGUI = new HolidayScheduler(); // holiday gui object
            holidaysGUI.setLocationRelativeTo(null); // centers window
            holidaysGUI.setVisible(true); // make visible
        }
    }//GEN-LAST:event_scheduleHolidaysButtonActionPerformed

    /**
     * Action performed method for delete button
     *
     * @param evt
     */
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (!postponeToggleButton.isSelected()) { // if postpone button is not selected
            if (scheduledTasks.getSelectedIndex() >= 0 && scheduledTasks.getSelectedIndex() < ReadScheduleFile.getScheduledEventData().size()) { // if there is a selection
                ReadScheduleFile.getScheduledEventData().remove(scheduledTasks.getSelectedIndex());
                int counter = 0; // counter
                try (BufferedWriter bw = new BufferedWriter(new FileWriter(PathConstants.scheduleFilePath))) { // write to file
                    for (Line genericEventData : ReadScheduleFile.getScheduledEventData()) { // loop through all indexes
                        genericEventData.setEventID(counter); // make the events in ascending order
                        bw.write(genericEventData.getEventID() + " @ " + genericEventData.getName() + " @ " + genericEventData.getPath() + " @ " + genericEventData.getStartTime() + " @ " + genericEventData.getEndTime() + " @ " + genericEventData.getDate() + " @ "); // format and write
                        counter++; // increment
                        bw.newLine(); // new line
                    }
                    bw.flush(); // flush the stream
                    bw.close(); // close file
                } catch (IOException e) {
                    System.out.println("IO Exception");
                }
                populateScheduledBox(true); // update scheduled box
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * Action performed method for modify button
     *
     * @param evt
     */
    private void modifyTasksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyTasksButtonActionPerformed
        if (!postponeToggleButton.isSelected()) { // if postpone button is not selected
            if (scheduledTasks.getSelectedIndex() >= 0) { // if there is a selection
                ModifyTask modifyGUI = new ModifyTask(scheduledTasks.getSelectedIndex()); // modify task gui object
                modifyGUI.setLocationRelativeTo(null); // centers window
                modifyGUI.setVisible(true); // make visible
            }
        }
    }//GEN-LAST:event_modifyTasksButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateAndTimeLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JScrollPane infoPane;
    private javax.swing.JTextArea informationBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel minutesLabel;
    private javax.swing.JButton modifyTasksButton;
    private javax.swing.JToggleButton overrideToggleButton;
    private javax.swing.JTextField postponeDurationInMinutes;
    private javax.swing.JToggleButton postponeToggleButton;
    private javax.swing.JButton propertiesButton;
    private javax.swing.JButton scheduleCommandButton;
    private javax.swing.JButton scheduleHolidaysButton;
    private javax.swing.JList scheduledTasks;
    private javax.swing.JLabel scheduledTasksLabel;
    private javax.swing.JScrollPane scheduledTasksPane;
    private javax.swing.JButton startNowButton;
    // End of variables declaration//GEN-END:variables
}
