package automatedsequence.gui;

import automatedsequence.fileInput.OCanada;
import automatedsequence.fileInput.ReadOCanadaFile;
import automatedsequence.fileOutput.WriteToOCanadaFile;
import java.io.File;
import javax.swing.AbstractListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Purpose: Properties Class
 *
 * @author Brian Ho, Max Romanoff, Conor Norman 
 * June 5 2014
 */
public class OCanadaVersionProperties extends javax.swing.JFrame {

    private AbstractListModel tableModel;
    private String[] fileInformation;

    /**
     * Creates new form Properties and initializes it's components
     */
    public OCanadaVersionProperties() {
        populatePathBox(false);
        initComponents();
        setLocationRelativeTo(null); // centres window
        setVisible(true); // make visible
    }

    /**
     * Method populates the path box with O'Canada paths
     *
     * @param refresh true if updating
     */
    public void populatePathBox(boolean refresh) {
        fileInformation = new String[ReadOCanadaFile.getOCanadaVersionData().size()]; // make an array the same size as the OCanadaVersion arraylist

        for (OCanada oCanadaVersionData : ReadOCanadaFile.getOCanadaVersionData()) { // loops through all indexes
            fileInformation[oCanadaVersionData.getID()] = oCanadaVersionData.getPath(); // populates the array
        }
        tableModel = new AbstractListModel() {
            @Override
            public int getSize() {
                return fileInformation.length;
            }

            @Override
            public Object getElementAt(int i) {
                return fileInformation[i];
            }
        };
        if (refresh) { // true if updating
            oCanadaVersions.setModel(tableModel); // set the model
            oCanadaVersions.revalidate(); // revalidate
            oCanadaVersions.repaint(); // refreshes
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oCanadaVersionsLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        oCanadaVersions = new javax.swing.JList();
        doneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Properties");
        setResizable(false);

        oCanadaVersionsLabel.setText("O'Canada Versions:");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        oCanadaVersions.setModel(tableModel);
        jScrollPane2.setViewportView(oCanadaVersions);

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oCanadaVersionsLabel)
                        .addGap(480, 480, 480))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(oCanadaVersionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removeButton)
                        .addComponent(doneButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action performed method for the remove button, it removes any selected
     * ocanada version
     *
     * @param evt
     */
    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        new AuthenticationDialogue("REMOVE_OCANADA_VERSION");
    }//GEN-LAST:event_removeButtonActionPerformed

    public void removeOCanadaVersion() {
        if (oCanadaVersions.getSelectedIndex() >= 0 && oCanadaVersions.getSelectedIndex() < ReadOCanadaFile.getOCanadaVersionData().size()) { // if there is a selection
            ReadOCanadaFile.getOCanadaVersionData().remove(oCanadaVersions.getSelectedIndex()); // remove the index
            WriteToOCanadaFile.reorderAndWrite(); // deletes, reorders indexes and writes to ocanada file
            populatePathBox(true); // update the box to show deletion
        } else { // nothing selected
            new Error("Please select an item to remove!"); // passes string
        }
    }

    /**
     * Action performed method for the add button, opens a browse window
     *
     * @param evt
     */
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        new AuthenticationDialogue("ADD_OCANADA_VERSION");
    }//GEN-LAST:event_addButtonActionPerformed

    public void addOCanadaVersion() {
        JFileChooser chooser = new JFileChooser(); // file chooser window
        FileFilter filter = new FileNameExtensionFilter("MP3 Files", "mp3", "mpeg3"); // mp3
        File dir = new File(System.getProperty("user.dir"));
        chooser.setCurrentDirectory(dir); // set current directory to program location folder
        chooser.setFileFilter(filter); // sets the filter
        chooser.setAcceptAllFileFilterUsed(false); // disallows all files option
        chooser.showOpenDialog(null);
        File fileToChoose = chooser.getSelectedFile(); // get the selected file
        try {
            String pathOfFile = fileToChoose.getAbsolutePath(); // get the path
            ReadOCanadaFile.getOCanadaVersionData().add(new OCanada(ReadOCanadaFile.getOCanadaVersionData().size(), pathOfFile)); // make a new object 
            WriteToOCanadaFile.write(); // writes to ocanada file
        } catch (NullPointerException e) {
            System.out.println("No File Selected");
        }
        populatePathBox(true); // update box to show addition
    }

    /**
     * Action performed method for done button
     *
     * @param evt
     */
    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        dispose(); // close window
    }//GEN-LAST:event_doneButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList oCanadaVersions;
    private javax.swing.JLabel oCanadaVersionsLabel;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
