package automatedsequence.gui;

import automatedsequence.constants.PathConstants;
import automatedsequence.fileInput.Line;
import automatedsequence.fileInput.ReadFile;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.AbstractListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author Brian
 */
public class Properties extends javax.swing.JFrame {
    
    private AbstractListModel tableModel, completedModel;
    private static String[] fileInformation;
    /**
     * Creates new form Properties
     */
    public Properties() {
        populatePathBox(false);
        initComponents();
    }
    
    public void populatePathBox(boolean refresh) {
        fileInformation = new String[ReadFile.getGenericEventData().size()];
        for (Line genericEventData : ReadFile.getGenericEventData()) {
            fileInformation[genericEventData.getEventID()] = genericEventData.getPath();
        }
        tableModel = new AbstractListModel() {
            @Override
            public int getSize() {
                return fileInformation.length;
            }

            @Override
            public Object getElementAt(int i) {
                return fileInformation[i];
            }
        };
        if (refresh) {
            oCanadaVersions.repaint(); // refreshes
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        morningRushPathTextBox = new javax.swing.JTextField();
        browseForMorningRush = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        oCanadaPathTextBox = new javax.swing.JTextField();
        browseForOCanada = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        oCanadaVersions = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Current Morning Rush Song:");

        morningRushPathTextBox.setText(ReadFile.getGenericEventData().get(0).getPath());
        morningRushPathTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morningRushPathTextBoxActionPerformed(evt);
            }
        });

        browseForMorningRush.setText("Browse");
        browseForMorningRush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseForMorningRushActionPerformed(evt);
            }
        });

        jLabel2.setText("\"Please stand up for O'Canada\":");

        oCanadaPathTextBox.setText(ReadFile.getGenericEventData().get(0).getPath());

        browseForOCanada.setText("Browse");
        browseForOCanada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseForOCanadaActionPerformed(evt);
            }
        });

        jLabel3.setText("O'Canada Versions:");

        addButton.setText("Add");

        removeButton.setText("Remove");

        oCanadaVersions.setModel(tableModel);
        jScrollPane2.setViewportView(oCanadaVersions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(morningRushPathTextBox)
                                    .addComponent(oCanadaPathTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(browseForMorningRush)
                                    .addComponent(browseForOCanada)))
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(morningRushPathTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseForMorningRush))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oCanadaPathTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseForOCanada)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseForMorningRushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseForMorningRushActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File fileToChoose = chooser.getSelectedFile();
        //ReadFile.getGenericEventData().add(new Line(ReadFile.getGenericEventData().size() , pathOfFile, 100000));
        try {
            String pathOfFile = fileToChoose.getAbsolutePath();
            morningRushPathTextBox.setText(pathOfFile);
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(PathConstants.schedulePathFile))) {
                for (Line genericEventData : ReadFile.getGenericEventData()) {
                    bw.write(genericEventData.getEventID() + " @ " + genericEventData.getName() + " @ " + genericEventData.getPath() + " @ " + genericEventData.getStartTime() + " @ " + genericEventData.getEndTime() + " @ " + genericEventData.getDate() + " @ ");
                    bw.newLine();
                }
                bw.flush();
                bw.close();
            } catch (IOException e) {
                System.out.println("IO Exception");
            }
        } catch (NullPointerException e) {
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_browseForMorningRushActionPerformed

    private void browseForOCanadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseForOCanadaActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File fileToChoose = chooser.getSelectedFile();
        try {
            String pathOfFile = fileToChoose.getAbsolutePath();
            oCanadaPathTextBox.setText(pathOfFile);
            //ReadFile.getGenericEventData().add(new Line(ReadFile.getGenericEventData().size() , pathOfFile, 100000));
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(PathConstants.schedulePathFile))) {
                for (Line genericEventData : ReadFile.getGenericEventData()) {
                    bw.write(genericEventData.getEventID() + " @ " + genericEventData.getName() + " @ " + genericEventData.getPath() + " @ " + genericEventData.getStartTime() + " @ " + genericEventData.getEndTime() + " @ " + genericEventData.getDate() + " @ ");
                    bw.newLine();
                }
                bw.flush();
                bw.close();
            } catch (IOException e) {
                System.out.println("IO Exception");
            }
            System.out.println(ReadFile.getGenericEventData().get(0).getPath());
        } catch (NullPointerException e) {
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_browseForOCanadaActionPerformed

    private void morningRushPathTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morningRushPathTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_morningRushPathTextBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton browseForMorningRush;
    private javax.swing.JButton browseForOCanada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField morningRushPathTextBox;
    private javax.swing.JTextField oCanadaPathTextBox;
    private javax.swing.JList oCanadaVersions;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
